title: Marc De La Cruz
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

include: [_pages]

defaults:
  -
    scope:
      path: _pages/projects
    values:
      layout: default

callouts_level: quiet # or loud
callouts:
  note2:
    title: 💡 Code Explanation
    color: grey-dk
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Skills Demonstrated
    color: blue
  warning:
    title: Warning
    color: red

logo: "/assets/images/marcdlclogo_g.png"