title: Marc's Cybersecurity Portfolio
description: Cybersecurity Portfolio for Marc De La Cruz
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  LinkedIn: https://linkedin.com/in/marcdlc

include: [_pages]

defaults:
  -
    scope:
      path: _pages/projects
    values:
      layout: default

callouts_level: quiet # or loud
callouts:
  note:
    title: Skills Demonstrated
    color: blue
  note2:
    title: 💡 Code Explanation
    color: grey-dk
  note3:
    title: Note
    color: yellow

logo: "/assets/images/marcdlc_logo.png"

nav_external_links:
  - title: My LinkedIn
    url: https://www.linkedin.com/in/marcdlc/